import json
from typing import Type
from llama_cpp import Llama
from pydantic import ValidationError
from src.llm_interface.llm_base import AbstractLLM, SupportsStructuredOutput, T


class LlamaCppLLM(AbstractLLM, SupportsStructuredOutput):
    """
    Concrete implementation of AbstractLLM using the llama.cpp backend.
    
    This class handles prompt generation, structured output parsing via Pydantic,
    and (optionally) streaming token generation.
    """

    def __init__(
        self,
        llama: Llama,
        temperature: float = 0.0,
        max_tokens: int = 256,
        stop: list[str] = None,
    ):
        """
        Initialize the LlamaCppLLM.

        Args:
            llama (Llama): An instance of llama_cpp.Llama with a loaded GGUF model.
            temperature (float): Sampling temperature (controls randomness). Default is 0.0 (greedy).
            max_tokens (int): Maximum number of tokens to generate per completion.
            stop (list[str], optional): Stop sequences to halt generation. Defaults to common tokens.
        """
        self.llama = llama
        self.temperature = temperature
        self.max_tokens = max_tokens
        self.stop = stop or ["</s>", "Answer:", "\n\n"]

    def generate(self, prompt: str, **kwargs) -> str:
        """
        Generate a text response from a prompt.

        Args:
            prompt (str): The input prompt to feed into the model.
            **kwargs: Optional overrides for temperature, max_tokens, and stop.

        Returns:
            str: The model's generated text.
        """
        response = self.llama(
            prompt=prompt,
            temperature=kwargs.get("temperature", self.temperature),
            max_tokens=kwargs.get("max_tokens", self.max_tokens),
            stop=kwargs.get("stop", self.stop),
        )
        return response["choices"][0]["text"]

    def stream(self, prompt: str, **kwargs):
        """
        Stream tokens as they are generated by the model (optional use).

        Args:
            prompt (str): The input prompt to feed into the model.
            **kwargs: Optional overrides for temperature, max_tokens, and stop.

        Yields:
            str: Incremental token chunks as they are generated.
        """
        stream = self.llama.create_completion(
            prompt=prompt,
            stream=True,
            temperature=kwargs.get("temperature", self.temperature),
            max_tokens=kwargs.get("max_tokens", self.max_tokens),
            stop=kwargs.get("stop", self.stop),
        )
        for chunk in stream:
            yield chunk["choices"][0]["text"]

    def generate_structured(self, prompt: str, schema: Type[T]) -> T:
        """
        Generate a structured output conforming to a given Pydantic schema.

        Assumes the prompt will elicit a valid JSON object matching the schema.

        Args:
            prompt (str): A prompt designed to return a JSON-formatted object.
            schema (Type[T]): A Pydantic model class used to validate the result.

        Returns:
            T: An instance of the provided schema populated with model output.
        """
        raw_output = self.generate(prompt)

        try:
            data = json.loads(raw_output)
            return schema.model_validate(data)
        except (json.JSONDecodeError, ValidationError) as e:
            raise ValueError(f"Failed to parse structured output: {e}")
