Pairs:
  schema: "src.schemas.pairs_schema.PairsSchema"
  entities: ["entity_1", "entity_2"]
  prompt: "prompts/pairs_prompt.txt"
  max_tokens: 300
  temperature: 0.6
  pairs_per_prompt: 1

DualPairs:
  schema: "src.schemas.dual_pairs_schema.DualPairsSchema"
  entities: ["entity_1a", "entity_1a, entity_2a", "entity_2b"]
  prompt: "prompts/dual_pairs_prompt.txt"
  max_tokens: 300
  temperature: 0.6
  pairs_per_prompt: 2

DummyTask:
    schema: "src.schemas.dummy_schema.DummySchema"
    temperature: 0.6
    max_tokens: 100